const projectsJavascript = [
	{
		link: 'GPEbzj',
		imgUrl: 'GPEbzj-320.webp?version=1545835628',
		date: '26-12-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 13,
		title: 'Merry Christmas!',
		tags: ['animation', 'image', 'background-position', 'border']
	},
	{
		link: 'pZKrYZ',
		imgUrl: 'pZKrYZ-512.webp?version=1536858191',
		date: '04-08-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 38,
		title: 'Template Responsive',
		tags: ['template', 'responsive', 'hamburger', 'menu']
	},
	{
		link: 'rrrVbV',
		imgUrl: 'rrrVbV-512.webp?version=1563829720',
		date: '05-08-2018',
		technology: 'Javascript',
		isFavorite: true,
		likes: 1,
		views: 371,
		title: 'Password Generator',
		tags: ['form', 'responsive', 'border', 'clipboard', 'button']
	},
	{
		link: 'MBGyRe',
		imgUrl: 'MBGyRe-512.webp?version=1536859860',
		date: '02-08-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 5,
		views: 241,
		title: 'Menu Responsive Hamburger',
		tags: ['menu', 'responsive', 'hamburger', 'drop-down']
	},
	{
		link: 'NBybZr',
		imgUrl: 'NBybZr-512.webp?version=1536856436',
		date: '31-07-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 248,
		title: 'Form Foundation Zurb',
		tags: ['form', 'library', 'responsive', 'shadow', 'button', 'checkbox']
	},
	{
		link: 'mKwQgM',
		imgUrl: 'mKwQgM-512.webp?version=1533835398',
		date: '14-06-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 3,
		views: 1672,
		title: 'Scroll Click Dynamic',
		tags: ['scroll', 'background-clip', 'animation', 'responsive']
	},
	{
		link: 'yxvMVJ',
		imgUrl: 'yxvMVJ-320.webp?version=1599585273',
		date: '11-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 57,
		views: 14582,
		title: 'Preloader responsive',
		tags: ['preloader', 'responsive', 'animation']
	},
	{
		link: 'yxvgOw',
		imgUrl: 'yxvgOw-320.webp?version=1599585476',
		date: '11-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 22,
		views: 3542,
		title: 'Slider Responsive',
		tags: ['slider', 'responsive', 'keyboard', 'animation', 'backface-visibility', 'mouse']
	},
	{
		link: 'OovERV',
		imgUrl: 'OovERV-320.webp?version=1599585563',
		date: '12-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 13,
		views: 1388,
		title: 'Card Modal',
		tags: ['card', 'modal', 'shadow', 'button', '3d', 'keydown']
	},
	{
		link: 'EeExbj',
		imgUrl: 'EeExbj-320.webp?version=1536663310',
		date: '11-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 3,
		views: 840,
		title: 'Navegation Tabs Responsive',
		tags: ['tabs', 'responsive', 'hover', 'card']
	},
	{
		link: 'WyjaJj',
		imgUrl: 'WyjaJj-512.webp?version=1533835292',
		date: '13-06-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 776,
		title: 'Scroll Detection',
		tags: ['scroll']
	},
	{
		link: 'pKEoPN',
		imgUrl: 'pKEoPN-512.webp?version=1631037968',
		date: '07-06-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 4,
		views: 1006,
		title: 'Login Form',
		tags: ['form', 'button', 'shadow', 'responsive']
	},
	{
		link: 'PdRbGq',
		imgUrl: 'PdRbGq-320.webp?version=1536853338',
		date: '11-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 6,
		views: 693,
		title: 'Footer Mobile',
		tags: ['footer', 'mobile', 'animation', 'hover', 'shadow', 'border', 'dark-theme']
	},
	{
		link: 'XPEeBP',
		imgUrl: 'XPEeBP-320.webp?version=1536700447',
		date: '12-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 8,
		views: 708,
		title: 'Form Contact Responsive',
		tags: ['form', 'responsive', 'button', 'dark-theme', 'sound']
	},
	{
		link: 'BOYmLr',
		imgUrl: 'BOYmLr-320.webp?version=1536703445',
		date: '11-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 965,
		title: 'Modals Responsive',
		tags: ['modal', 'responsive', 'sound', 'data', 'button', 'shadow', '3d']
	},
	{
		link: 'yLBobVq',
		imgUrl: 'yLBobVq-512.webp?version=1599586121',
		date: '31-08-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 18,
		views: 822,
		title: 'Portfolio',
		tags: ['card', 'responsive', 'image', 'search', 'data', 'library']
	},
	{
		link: 'eqBZMm',
		imgUrl: 'eqBZMm-512.webp?version=1564180531',
		date: '27-07-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 201,
		title: 'Image Reveal On Scroll',
		tags: ['scroll', 'image']
	},
	{
		link: 'jgVqEe',
		imgUrl: 'jgVqEe-512.webp?version=1564763049',
		date: '27-07-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 4,
		views: 180,
		title: 'Change Opacity On Scroll',
		tags: ['scroll', 'animation', 'responsive']
	},
	{
		link: 'ExKxpLq',
		imgUrl: 'ExKxpLq-512.webp?version=1596656986',
		date: '06-08-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 31,
		views: 2176,
		title: 'Effect Parallax',
		tags: ['parallax', 'data', 'responsive', 'mouse']
	},
	{
		link: 'RXazEa',
		imgUrl: 'RXazEa-512.webp?version=1563997369',
		date: '25-07-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 3,
		views: 294,
		title: 'Cursor Focus',
		tags: ['mouse', 'glass', 'cursor', 'filter', 'shadow']
	},
	{ 
		link: 'QejeJW',
		imgUrl: 'QejeJW-512.webp?version=1613738463',
		date: '23-07-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 14,
		views: 1401,
		title: '3d Mousemove Parallax',
		tags: ['parallax', 'mouse', 'image', 'responsive']
	},
	{
		link: 'GRZRdyB',
		imgUrl: 'GRZRdyB-512.webp?version=1596656530',
		date: '06-08-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 85,
		title: 'Effect Flying Rocket',
		tags: ['animation', 'blur', 'mouse', 'shadow']
	},
	{
		link: 'KKVdgrq',
		imgUrl: 'KKVdgrq-512.webp?version=1601904077',
		date: '08-06-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 155,
		title: 'Effect Video Sphere',
		tags: ['video', 'geometry', 'sphere', 'shadow', 'library', 'responsive']
	},
	{
		link: 'LMNYWg',
		imgUrl: 'LMNYWg-320.webp?version=1544797055',
		date: '14-12-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 16,
		title: 'Slider',
		tags: ['slider']
	},
	{
		link: 'KrPLQM',
		imgUrl: 'KrPLQM-320.webp?version=1541531170',
		date: '03-11-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 6,
		views: 1002,
		title: 'Slider responsive',
		tags: ['slider', 'responsive', 'pagination']
	},
	{
		link: 'dQJpBg',
		imgUrl: 'dQJpBg-320.webp?version=1545086842',
		date: '21-11-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 5,
		views: 462,
		title: 'Modal animated',
		tags: ['modal', 'animation', 'responsive', 'form']
	},
	{
		link: 'jOVGamW',
		imgUrl: 'jOVGamW-512.webp?version=1613994292',
		date: '22-02-2021',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 157,
		title: 'Soft Drink',
		tags: ['animation', 'border', 'responsive', 'shadow']
	},
	{
		link: 'RwawJGd',
		imgUrl: 'RwawJGd-512.webp?version=1596656273',
		date: '06-08-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 168,
		title: 'Effect Starry Night',
		tags: ['animation', 'gradient', 'responsive', 'parallax', 'image']
	},
	{
		link: 'PEbbGM',
		imgUrl: 'PEbbGM-512.webp?version=1536858648',
		date: '24-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 233,
		title: 'Reloj Js',
		tags: ['clock']
	},
	{
		link: 'LqJmJm',
		imgUrl: 'LqJmJm-512.webp?version=1550155337',
		date: '14-02-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 1,
		views: 119,
		title: 'Admin Park',
		tags: ['form', 'button', 'shadow', 'modal', 'card', 'local-storage']
	},
	{
		link: 'agVWGz',
		imgUrl: 'agVWGz-512.webp?version=1561647743',
		date: '27-06-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 16,
		title: 'HTML5 Drag & Drop',
		tags: ['drag-drop', 'draggable', 'border', 'responsive']
	},
	{
		imgUrl: 'ZgXEPw-512.webp?version=1564788514',
		date: '02-08-2019',
		isFavorite: false,
		technology: 'Javascript',
		likes: 1,
		views: 138,
		link: 'ZgXEPw',
		title: 'Slide Image Comparison',
		tags: ['slider', 'mouse', 'responsive']
	},
	{
		imgUrl: 'PMzgKj-512.webp?version=1564065094',
		date: '25-07-2019',
		isFavorite: false,
		technology: 'Javascript',
		likes: 4,
		views: 269,
		link: 'PMzgKj',
		title: 'Effect Brick Falling',
		tags: ['mouse', 'hover', 'animation']
	},
	{
		link: 'pGRjbb',
		imgUrl: 'pGRjbb-512.webp?version=1548961836',
		date: '31-01-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 220,
		title: 'Lightbox Responsive',
		tags: ['responsive', 'cards', 'image', 'modal', 'grid']
	},
	{
		link: 'LebbxJ',
		imgUrl: 'LebbxJ-512.webp?version=1533391791',
		date: '24-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 241,
		title: 'Efect Typewriter',
		tags: ['typewriter']
	},
	{
		link: 'BJaMyv',
		imgUrl: 'BJaMyv-512.webp?version=1513115037',
		date: '13-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 5,
		title: 'Preloading Screen',
		tags: ['preloader', 'animation', 'responsive', 'border']
	},
	{
		link: 'YYKJom',
		imgUrl: 'YYKJom-512.webp?version=1536854551',
		date: '12-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 464,
		title: 'Social Media Expand',
		tags: ['footer', 'mobile', 'button', 'responsive']
	},
	{
		link: 'BxKGrE',
		imgUrl: 'BxKGrE-512.webp?version=1533828078',
		date: '25-04-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 95,
		title: 'Clipboard Minified',
		tags: ['clipboard', 'responsive', 'animation']
	},
	{
		link: 'KoPdpN',
		imgUrl: 'KoPdpN-512.webp?version=1533828780',
		date: '08-03-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 468,
		title: 'Table Responsive With Theme Dark',
		tags: ['table', 'responsive', 'dark-theme']
	},
	{
		link: 'jYyaGa',
		imgUrl: 'jYyaGa-512.webp?version=1536853892',
		date: '27-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 4,
		views: 702,
		title: 'Acordeon Responsive',
		tags: ['acordeon', 'responsive']
	},
	{
		link: 'EoZzvX',
		imgUrl: 'EoZzvX-512.webp?version=1533829393',
		date: '27-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 301,
		title: 'Social Media Expand',
		tags: ['footer', 'mobile', 'button', 'responsive']
	},
	{
		link: 'ZvBBgo',
		imgUrl: 'ZvBBgo-512.webp?version=1536859497',
		date: '24-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 195,
		title: 'Presentation Card Responsive',
		tags: ['card', 'slider', 'responsive']
	},
	{
		link: 'JjjxMmm',
		imgUrl: 'JjjxMmm-512.webp?version=1574186493',
		date: '20-11-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 3,
		views: 136,
		title: 'Page Scroll Progressbar',
		tags: ['gradient', 'scroll']
	},
	{
		link: 'Yzzgqvy',
		imgUrl: 'Yzzgqvy-512.webp?version=1574269822',
		date: '21-11-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 75,
		title: 'Effect Glitch',
		tags: ['image', 'responsive']
	},
	{
		link: 'rNaWWea',
		imgUrl: 'rNaWWea-512.webp?version=1576526031',
		date: '16-12-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 21,
		views: 811,
		title: 'Form Card Credit',
		tags: ['card', 'form', 'validation', 'clip-path', 'responsive']
	},
	{
		link: 'MNjjrz',
		imgUrl: 'MNjjrz-512.webp?version=1564157241',
		date: '26-07-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 769,
		title: 'Effect Parallax On Mouse move',
		tags: ['parallax', 'data', 'background-blend-mode', 'library']
	},
	{
		link: 'QWjGbBJ',
		imgUrl: 'QWjGbBJ-512.webp?version=1587481506',
		date: '21-04-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 4,
		views: 246,
		title: 'Effect Scroll Rainbow',
		tags: ['animation', 'blur', 'scroll', 'gradient', 'responsive']
	},
	{
		link: 'vYNgYpR',
		imgUrl: 'vYNgYpR-512.webp?version=1587573562',
		date: '22-04-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 7,
		views: 913,
		title: 'Effect Parallax Scrolling',
		tags: ['scroll', 'parallax', 'responsive', 'mix-blend-mode']
	},
	{
		link: 'EpqzBY',
		imgUrl: 'EpqzBY-320.webp?version=1534702495',
		date: '18-08-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 5,
		views: 362,
		title: 'Menu Dropdown Responsive',
		tags: ['menu', 'responsive', 'hamburger', 'drop-down', '3d']
	},
	{
		link: 'vjVRKR',
		imgUrl: 'vjVRKR-1280.webp?version=1533820548',
		date: '17-05-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 23,
		views: 3984,
		title: 'Menu',
		tags: ['menu', 'responsive', 'hamburger', 'hover']
	},
	{
		link: 'rvYrzO',
		imgUrl: 'rvYrzO-512.webp?version=1536856170',
		date: '08-05-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 386,
		title: 'Calculator',
		tags: ['responsive', 'shadow', 'calculator']
	},
	{
		link: 'ZEByLMj',
		imgUrl: 'ZEByLMj-512.webp?version=1613671119',
		date: '18-02-2021',
		technology: 'Javascript',
		isFavorite: false,
		likes: 6,
		views: 243,
		title: 'Cards',
		tags: ['card', 'hover', 'responsive', 'mouse']
	},
	{
		link: 'wvoepar',
		imgUrl: 'wvoepar-512.webp?version=1613673694',
		date: '19-02-2021',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 114,
		title: 'Slither Io',
		tags: ['games', 'mouse', 'radial-gradient', 'library', 'responsive']
	},
	{
		link: 'GRKymgL',
		imgUrl: 'GRKymgL-512.webp?version=1568650825',
		date: '06-09-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 11,
		views: 2683,
		title: 'Odometer Number Counter',
		tags: ['library', 'responsive']
	},
	{
		link: 'mddobvR',
		imgUrl: 'mddobvR-512.webp?version=1574252213',
		date: '20-11-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 1,
		views: 87,
		title: 'Effect Follow Mouse Cursor',
		tags: ['game', 'hover', 'mouse', 'responsive', 'getBoundingClientRect']
	},
	{
		link: 'eYmrmgM',
		imgUrl: 'eYmrmgM-512.webp?version=1578661401',
		date: '10-01-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 5,
		views: 237,
		title: 'Effect Slide Image Comparision',
		tags: ['slider', 'image', 'mouse']
	},
	{
		link: 'JjGYKJW',
		imgUrl: 'JjGYKJW-512.webp?version=1591623049',
		date: '08-06-2020',
		technology: 'Javascript',
		isFavorite: true,
		likes: 7,
		views: 184,
		title: 'Effect floating button',
		tags: ['button', 'footer', 'mobile', 'list', 'responsive']
	},
	{
		link: 'QWwrPoM',
		imgUrl: 'QWwrPoM-512.webp?version=1578951478',
		date: '12-01-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 8,
		views: 459,
		title: 'Youtube',
		tags: ['template', 'grid', 'menu', 'responsive']
	},
	{
		link: 'PowePzx',
		imgUrl: 'PowePzx-512.webp?version=1578669848',
		date: '10-01-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 3,
		views: 164,
		title: 'Digital clock',
		tags: ['clock', 'box-reflect', 'shadow', 'responsive']
	},
	{
		link: 'WNbJvbz',
		imgUrl: 'WNbJvbz-512.webp?version=1578663795',
		date: '10-01-2020',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 341,
		title: 'Effect Parallax Mousemove',
		tags: ['parallax', 'data', 'mouse', '3d', 'hover']
	},
	{
		link: 'PXryxY',
		imgUrl: 'PXryxY-512.webp?version=1547832730',
		date: '19-01-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 268,
		title: 'Template Bootstrap',
		tags: ['template', 'slider', 'animation', 'bootstrap', 'library', 'responsive']
	},
	{
		link: 'aPMEYq',
		imgUrl: 'aPMEYq-512.webp?version=1547590609',
		date: '16-01-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 121,
		title: 'Jackpot Game',
		tags: ['games', 'responsive']
	},
	{
		link: 'dwaRNz',
		imgUrl: 'dwaRNz-512.webp?version=1547505908',
		date: '15-01-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 1,
		views: 175,
		title: 'Archery Game',
		tags: ['game', 'animation', 'responsive']
	},
	{
		link: 'yGRbzL',
		imgUrl: 'yGRbzL-320.webp?version=1547170234',
		date: '11-01-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 85,
		title: 'Simon Game',
		tags: ['games', 'sound', 'modal', 'button', 'shadow', 'responsive']
	},
	{
		link: 'QzmvLp',
		imgUrl: 'QzmvLp-320.webp?version=1546726072',
		date: '05-01-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 138,
		title: 'Bubble Floating',
		tags: ['games', 'responsive', 'keyboard']
	},
	{
		link: 'pozdLgO',
		imgUrl: 'pozdLgO-512.webp?version=1568650859',
		date: '05-09-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 3,
		views: 256,
		title: 'Menu Amazon',
		tags: ['menu', 'responsive', 'drop-down', 'image', 'hamburger']
	},
	{
		link: 'bGboWJL',
		imgUrl: 'bGboWJL-512.webp?version=1568650863',
		date: '03-09-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 2,
		views: 395,
		title: 'Tooltip Js',
		tags: ['tooltip', 'shadow', 'hover', 'border', 'mouse', 'card']
	},
	{
		link: 'PEbbOw',
		imgUrl: 'PEbbOw-512.webp?version=1710089549',
		date: '24-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 42,
		title: 'Regresive Count Js',
		tags: ['countdown']
	},
	{
		link: 'EoNNwL',
		imgUrl: 'EoNNwL-512.webp?version=1536858968',
		date: '24-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 79,
		title: 'Modal Js',
		tags: ['modal', 'responsive']
	},
	{
		link: 'YYppxg',
		imgUrl: 'YYppxg-512.webp?version=1533392519',
		date: '24-12-2017',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 141,
		title: 'Modal Youtube Js Responsive',
		tags: ['modal', 'iframe', 'responsive']
	},
	{
		link: 'Oovgjz',
		imgUrl: 'Oovgjz-320.webp?version=1536852567',
		date: '12-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 113,
		title: 'Modals Flexbox Js Responsive',
		tags: ['modal', 'responsive', 'button', 'hover', 'shadow', '3d', 'keyboard']
	},
	{
		link: 'yxpodp',
		imgUrl: 'yxpodp-320.webp?version=1536853553',
		date: '09-09-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 412,
		title: 'Masonry Layout Js',
		tags: ['template', 'masonry', 'grid', 'responsive']
	},
	{
		link: 'VGyvzy',
		imgUrl: 'VGyvzy-320.webp?version=1536447155',
		date: '09-09-2018',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 69,
		title: 'Tester Responsive Js',
		tags: ['responsive', 'window']
	},
	{
		link: 'NQGLOK',
		imgUrl: 'NQGLOK-512.webp?version=1563811212',
		date: '22-07-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 6,
		views: 349,
		title: 'Water Fill On Scroll',
		tags: ['scroll', 'animation', 'shadow', 'border', 'responsive']
	},
	{
		link: 'roeNbr',
		imgUrl: 'roeNbr-320.webp?version=1545085245',
		date: '14-12-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 80,
		title: 'Calculator',
		tags: ['calculator', 'responsive', 'data', 'scroll', 'grid']
	},
	{
		link: 'EGvxer',
		imgUrl: 'EGvxer-320.webp?version=1545847440',
		date: '27-12-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 164,
		title: 'Masonry Grid Layout Responsive',
		tags: ['template', 'columns', 'responsive', 'cards']
	},
	{
		link: 'oNNBBdZ',
		imgUrl: 'oNNBBdZ-512.webp?version=1587482167',
		date: '22-10-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 62,
		title: 'Analog Clock',
		tags: ['clock', 'shadow', 'responsive']
	},
	{
		link: 'rXLVML',
		imgUrl: 'rXLVML-512.webp?version=1563998440',
		date: '25-07-2019',
		technology: 'Javascript',
		isFavorite: false,
		likes: 1,
		views: 255,
		title: 'Effect flip background',
		tags: ['hover', '3d', 'mouse']
	}
];