const projectsJavascript = [
	{
		link: 'GPEbzj',
		imgUrl: 'GPEbzj-320.webp?version=1545835628',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 10000000000,
		views: 500,
		title: 'Merry Christmas!',
		tags: ['animation', 'image', 'background-position', 'border']
	},
	{
		link: 'pZKrYZ',
		imgUrl: 'pZKrYZ-512.webp?version=1536858191',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Template Responsive',
		tags: ['template', 'layout', 'responsive', 'hamburger', 'menu']
	},
	{
		link: 'rrrVbV',
		imgUrl: 'rrrVbV-512.webp?version=1563829720',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 500,
		title: 'Password Generator',
		tags: ['form', 'responsive', 'border', 'password', 'clipboard', 'button']
	},
	{
		link: 'MBGyRe',
		imgUrl: 'MBGyRe-512.webp?version=1536859860',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Menu Responsive Hamburger',
		tags: ['menu', 'responsive', 'hamburger', 'drop-down']
	},
	{
		link: 'NBybZr',
		imgUrl: 'NBybZr-512.webp?version=1536856436',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Form Foundation Zurb',
		tags: ['form', 'library', 'responsive', 'shadow', 'button', 'checkbox']
	},
	{
		link: 'mKwQgM',
		imgUrl: 'mKwQgM-512.webp?version=1533835398',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Scroll Click Dynamic',
		tags: ['scroll', 'background-clip', 'animation', 'responsive']
	},
	{
		link: 'yxvMVJ',
		imgUrl: 'yxvMVJ-320.webp?version=1599585273',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Preloader responsive',
		tags: ['preloader', 'responsive', 'animation']
	},
	{
		link: 'yxvgOw',
		imgUrl: 'yxvgOw-320.webp?version=1599585476',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Slider Responsive',
		tags: ['slider', 'responsive', 'keyboard', 'animation', 'backface-visibility', 'mouse']
	},
	{
		link: 'OovERV',
		imgUrl: 'OovERV-320.webp?version=1599585563',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Card Modal',
		tags: ['card', 'modal', 'shadow', 'button', '3d', 'keydown']
	},
	{
		link: 'EeExbj',
		imgUrl: 'EeExbj-320.webp?version=1536663310',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Navegation Tabs Responsive',
		tags: ['tabs', 'responsive', 'hover', 'card']
	},
	{
		link: 'WyjaJj',
		imgUrl: 'WyjaJj-512.webp?version=1533835292',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Scroll Detection',
		tags: ['scroll']
	},
	{
		link: 'pKEoPN',
		imgUrl: 'pKEoPN-512.webp?version=1631037968',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Login Form',
		tags: ['form', 'button', 'shadow', 'responsive']
	},
	{
		link: 'PdRbGq',
		imgUrl: 'PdRbGq-320.webp?version=1536853338',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 100,
		title: 'Footer Mobile',
		tags: ['footer', 'mobile', 'animation', 'hover', 'shadow', 'border', 'dark-theme']
	},
	{
		link: 'XPEeBP',
		imgUrl: 'XPEeBP-320.webp?version=1536700447',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Form Contact Responsive',
		tags: ['form', 'responsive', 'button', 'dark-theme', 'sound']
	},
	{
		link: 'BOYmLr',
		imgUrl: 'BOYmLr-320.webp?version=1536703445',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 100,
		title: 'Modals Responsive',
		tags: ['modal', 'responsive', 'sound', 'data', 'button', 'shadow', '3d']
	},
	{
		link: 'yLBobVq',
		imgUrl: 'yLBobVq-512.webp?version=1599586121',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 2000,
		title: 'Portfolio',
		tags: ['card', 'responsive', 'image', 'search', 'data', 'library']
	},
	{
		link: 'eqBZMm',
		imgUrl: 'eqBZMm-512.webp?version=1564180531',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Image Reveal On Scroll',
		tags: ['scroll', 'image']
	},
	{
		link: 'jgVqEe',
		imgUrl: 'jgVqEe-512.webp?version=1564763049',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 1500,
		title: 'Change Opacity On Scroll',
		tags: ['scroll', 'animation', 'responsive']
	},
	{
		link: 'ExKxpLq',
		imgUrl: 'ExKxpLq-512.webp?version=1596656986',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Parallax',
		tags: ['parallax', 'data', 'responsive', 'mouse']
	},
	{
		link: 'RXazEa',
		imgUrl: 'RXazEa-512.webp?version=1563997369',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Cursor Focus',
		tags: ['mouse', 'glass', 'cursor', 'filter', 'shadow']
	},
	{
		link: 'QejeJW',
		imgUrl: 'QejeJW-512.webp?version=1613738463',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: '3d Mousemove Parallax',
		tags: ['parallax', 'mouse', 'image', 'responsive']
	},
	{
		link: 'GRZRdyB',
		imgUrl: 'GRZRdyB-512.webp?version=1596656530',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Flying Rocket',
		tags: ['animation', 'blur', 'mouse', 'shadow']
	},
	{
		link: 'KKVdgrq',
		imgUrl: 'KKVdgrq-512.webp?version=1601904077',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Video Sphere',
		tags: ['video', 'geometry', 'sphere', 'shadow', 'library', 'responsive']
	},
	{
		link: 'LMNYWg',
		imgUrl: 'LMNYWg-320.webp?version=1544797055',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Slider',
		tags: ['slider', 'lightbox']
	},
	{
		link: 'KrPLQM',
		imgUrl: 'KrPLQM-320.webp?version=1541531170',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Slider responsive',
		tags: ['slider', 'responsive', 'pagination']
	},
	{
		link: 'dQJpBg',
		imgUrl: 'dQJpBg-320.webp?version=1545086842',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Modal animated',
		tags: ['modal', 'animation', 'responsive', 'form']
	},
	{
		link: 'jOVGamW',
		imgUrl: 'jOVGamW-512.webp?version=1613994292',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Soft Drink',
		tags: ['animation', 'border', 'responsive', 'shadow']
	},
	{
		link: 'RwawJGd',
		imgUrl: 'RwawJGd-512.webp?version=1596656273',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Starry Night',
		tags: ['animation', 'gradient', 'responsive', 'parallax', 'image']
	},
	{
		link: 'PEbbGM',
		imgUrl: 'PEbbGM-512.webp?version=1536858648',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 150,
		title: 'Reloj Js',
		tags: ['clock']
	},
	{
		link: 'LqJmJm',
		imgUrl: 'LqJmJm-512.webp?version=1550155337',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 510,
		title: 'Admin Park',
		tags: ['form', 'button', 'shadow', 'modal', 'card', 'local-storage']
	},
	{
		link: 'agVWGz',
		imgUrl: 'agVWGz-512.webp?version=1561647743',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 1000,
		title: 'HTML5 Drag & Drop',
		tags: ['drag-drop', 'draggable', 'border', 'responsive']
	},
	{
		imgUrl: 'ZgXEPw-512.webp?version=1564788514',
		date: '01-01-2022',
		isFavorite: false,
		technology: 'Javascript',
		likes: 0,
		views: 2500,
		link: 'ZgXEPw',
		title: 'Slide Image Comparison',
		tags: ['slider', 'mouse', 'responsive']
	},
	{
		imgUrl: 'PMzgKj-512.webp?version=1564065094',
		date: '01-01-2022',
		isFavorite: false,
		technology: 'Javascript',
		likes: 0,
		views: 5000,
		link: 'PMzgKj',
		title: 'Effect Brick Falling',
		tags: ['mouse', 'hover', 'animation']
	},
	{
		link: 'pGRjbb',
		imgUrl: 'pGRjbb-512.webp?version=1548961836',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 15000,
		title: 'Lightbox Responsive',
		tags: ['lightbox', 'responsive', 'cards', 'image', 'modal', 'grid']
	},
	{
		link: 'LebbxJ',
		imgUrl: 'LebbxJ-512.webp?version=1533391791',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 150,
		title: 'Efect Typewriter',
		tags: ['typewriter']
	},
	{
		link: 'BJaMyv',
		imgUrl: 'BJaMyv-512.webp?version=1513115037',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 100,
		title: 'Preloading Screen',
		tags: ['preloader', 'animation', 'responsive', 'border']
	},
	{
		link: 'YYKJom',
		imgUrl: 'YYKJom-512.webp?version=1536854551',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 1000,
		title: 'Social Media Expand',
		tags: ['footer', 'mobile', 'button', 'responsive']
	},
	{
		link: 'BxKGrE',
		imgUrl: 'BxKGrE-512.webp?version=1533828078',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 10000,
		title: 'Clipboard Minified',
		tags: ['clipboard', 'responsive', 'animation']
	},
	{
		link: 'KoPdpN',
		imgUrl: 'KoPdpN-512.webp?version=1533828780',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Table Responsive With Theme Dark',
		tags: ['table', 'responsive', 'dark-theme']
	},
	{
		link: 'jYyaGa',
		imgUrl: 'jYyaGa-512.webp?version=1536853892',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Acordeon Responsive',
		tags: ['acordeon', 'responsive']
	},
	{
		link: 'EoZzvX',
		imgUrl: 'EoZzvX-512.webp?version=1533829393',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Social Media Expand',
		tags: ['footer', 'mobile', 'button', 'responsive']
	},
	{
		link: 'ZvBBgo',
		imgUrl: 'ZvBBgo-512.webp?version=1536859497',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Presentation Card Responsive',
		tags: ['card', 'slider', 'responsive']
	},
	{
		link: 'JjjxMmm',
		imgUrl: 'JjjxMmm-512.webp?version=1574186493',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Page Scroll Progressbar',
		tags: ['gradient', 'scroll']
	},
	{
		link: 'Yzzgqvy',
		imgUrl: 'Yzzgqvy-512.webp?version=1574269822',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Glitch',
		tags: ['image', 'responsive']
	},
	{
		link: 'rNaWWea',
		imgUrl: 'rNaWWea-512.webp?version=1576526031',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 500,
		title: 'Form Card Credit',
		tags: ['card', 'form', 'validation', 'clip-path', 'polygon', 'responsive']
	},
	{
		link: 'MNjjrz',
		imgUrl: 'MNjjrz-512.webp?version=1564157241',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Parallax On Mouse move',
		tags: ['parallax', 'data', 'background-blend-mode', 'library']
	},
	{
		link: 'QWjGbBJ',
		imgUrl: 'QWjGbBJ-512.webp?version=1587481506',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Scroll Rainbow',
		tags: ['animation', 'blur', 'scroll', 'gradient', 'responsive']
	},
	{
		link: 'vYNgYpR',
		imgUrl: 'vYNgYpR-512.webp?version=1587573562',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect Parallax Scrolling',
		tags: ['scroll', 'parallax', 'responsive', 'mix-blend-mode']
	},
	{
		link: 'EpqzBY',
		imgUrl: 'EpqzBY-320.webp?version=1534702495',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Menu Dropdown Responsive',
		tags: ['menu', 'responsive', 'hamburger', 'drop-down', '3d']
	},
	{
		link: 'vjVRKR',
		imgUrl: 'vjVRKR-1280.webp?version=1533820548',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 1000,
		title: 'Menu',
		tags: ['menu', 'responsive', 'hamburger', 'hover']
	},
	{
		link: 'rvYrzO',
		imgUrl: 'rvYrzO-512.webp?version=1536856170',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 2000,
		title: 'Calculator',
		tags: ['responsive', 'shadow', 'calculator']
	},
	{
		link: 'ZEByLMj',
		imgUrl: 'ZEByLMj-512.webp?version=1613671119',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 3000,
		title: 'Cards',
		tags: ['card', 'hover', 'responsive', 'mouse']
	},
	{
		link: 'wvoepar',
		imgUrl: 'wvoepar-512.webp?version=1613673694',
		date: '01-01-2019',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 100,
		title: 'Slither Io',
		tags: ['games', 'mouse', 'radial-gradient', 'library', 'responsive']
	},
	{
		link: 'GRKymgL',
		imgUrl: 'GRKymgL-512.webp?version=1568650825',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 50,
		title: 'Odometer Number Counter',
		tags: ['library', 'responsive']
	},
	{
		link: 'mddobvR',
		imgUrl: 'mddobvR-512.webp?version=1574252213',
		date: '01-01-2020',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 5,
		title: 'Effect Follow Mouse Cursor',
		tags: ['game', 'hover', 'mouse', 'responsive', 'getBoundingClientRect']
	},
	{
		link: 'eYmrmgM',
		imgUrl: 'eYmrmgM-512.webp?version=1578661401',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 3,
		title: 'Effect Slide Image Comparision',
		tags: ['slider', 'image', 'mouse']
	},
	{
		link: 'JjGYKJW',
		imgUrl: 'JjGYKJW-512.webp?version=1591623049',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 20,
		title: 'Effect floating button',
		tags: ['button', 'footer', 'mobile', 'list', 'responsive']
	},
	{
		link: 'QWwrPoM',
		imgUrl: 'QWwrPoM-512.webp?version=1578951478',
		date: '01-01-2018',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 10,
		title: 'Youtube',
		tags: ['template', 'layout', 'grid', 'menu', 'responsive']
	},
	{
		link: 'PowePzx',
		imgUrl: 'PowePzx-512.webp?version=1578669848',
		date: '01-01-2023',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 10,
		title: 'Digital clock',
		tags: ['clock', 'box-reflect', 'shadow', 'responsive']
	},
	{
		link: 'WNbJvbz',
		imgUrl: 'WNbJvbz-512.webp?version=1578663795',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 10,
		title: 'Effect Parallax Mousemove',
		tags: ['parallax', 'data', 'mouse', '3d', 'hover']
	},
	{
		link: 'PXryxY',
		imgUrl: 'PXryxY-512.webp?version=1547832730',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 10,
		title: 'Template Bootstrap',
		tags: ['template', 'layout', 'slider', 'animation', 'bootstrap', 'library', 'responsive']
	},
	{
		link: 'aPMEYq',
		imgUrl: 'aPMEYq-512.webp?version=1547590609',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 20,
		title: 'Jackpot Game',
		tags: ['games', 'responsive']
	},
	{
		link: 'dwaRNz',
		imgUrl: 'dwaRNz-512.webp?version=1547505908',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 500,
		title: 'Archery Game',
		tags: ['game', 'animation', 'responsive']
	},
	{
		link: 'yGRbzL',
		imgUrl: 'yGRbzL-320.webp?version=1547170234',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 50,
		title: 'Simon Game',
		tags: ['games', 'sound', 'modal', 'button', 'shadow', 'responsive']
	},
	{
		link: 'QzmvLp',
		imgUrl: 'QzmvLp-320.webp?version=1546726072',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 20,
		title: 'Bubble Floating',
		tags: ['games', 'responsive', 'keyboard']
	},
	{
		link: 'pozdLgO',
		imgUrl: 'pozdLgO-512.webp?version=1568650859',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 21,
		title: 'Menu Amazon',
		tags: ['menu', 'responsive', 'drop-down', 'image', 'hamburger']
	},
	{
		link: 'bGboWJL',
		imgUrl: 'bGboWJL-512.webp?version=1568650863',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 31,
		title: 'Tooltip Js',
		tags: ['tooltip', 'shadow', 'hover', 'border', 'mouse', 'card']
	},
	{
		link: 'PEbbOw',
		imgUrl: 'PEbbOw-512.webp?version=1710089549',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 0,
		title: 'Regresive Count Js',
		tags: ['countdown']
	},
	{
		link: 'EoNNwL',
		imgUrl: 'EoNNwL-512.webp?version=1536858968',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 20,
		title: 'Modal Js',
		tags: ['modal', 'responsive']
	},
	{
		link: 'YYppxg',
		imgUrl: 'YYppxg-512.webp?version=1533392519',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 400,
		title: 'Modal Youtube Js Responsive',
		tags: ['modal', 'iframe', 'responsive']
	},
	{
		link: 'Oovgjz',
		imgUrl: 'Oovgjz-320.webp?version=1536852567',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 300,
		title: 'Modals Flexbox Js Responsive',
		tags: ['modal', 'responsive', 'button', 'hover', 'shadow', '3d', 'keyboard']
	},
	{
		link: 'yxpodp',
		imgUrl: 'yxpodp-320.webp?version=1536853553',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 350,
		title: 'Masonry Layout Js',
		tags: ['template', 'layout', 'masonry', 'grid', 'responsive']
	},
	{
		link: 'VGyvzy',
		imgUrl: 'VGyvzy-320.webp?version=1536447155',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: true,
		likes: 0,
		views: 250,
		title: 'Tester Responsive Js',
		tags: ['responsive', 'window']
	},
	{
		link: 'NQGLOK',
		imgUrl: 'NQGLOK-512.webp?version=1563811212',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Water Fill On Scroll',
		tags: ['scroll', 'animation', 'shadow', 'border', 'responsive']
	},
	{
		link: 'roeNbr',
		imgUrl: 'roeNbr-320.webp?version=1545085245',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 10,
		title: 'Calculator',
		tags: ['calculator', 'responsive', 'data', 'scroll', 'grid']
	},
	{
		link: 'EGvxer',
		imgUrl: 'EGvxer-320.webp?version=1545847440',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Masonry Grid Layout Responsive',
		tags: ['template', 'columns', 'layout', 'responsive', 'cards']
	},
	{
		link: 'oNNBBdZ',
		imgUrl: 'oNNBBdZ-512.webp?version=1587482167',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Analog Clock',
		tags: ['clock', 'shadow', 'responsive']
	},
	{
		link: 'rXLVML',
		imgUrl: 'rXLVML-512.webp?version=1563998440',
		date: '01-01-2022',
		technology: 'Javascript',
		isFavorite: false,
		likes: 0,
		views: 500,
		title: 'Effect flip background',
		tags: ['hover', '3d', 'mouse']
	}
];